docs/packages/about.md, mkdocs.yml
=> Python packages tab landing page

docs/packages/development/howto_venv.md, mkdocs.yml
To raise awareness and avoid people ruining their python installation way too often before stumbling over this, a quick How-to setup a venv would be nice
=> Add Creation of virtual enviroments to How-to

README.md, docs/resources/howto/teleworking.md, docs/resources/howto/wiki.md, mkdocs.yml
=> #29 Add a "How to edit/add a Wiki page" page

docs/resources/publications.md
add major publications from the last year to the publication page
=> Complete publication list

docs/resources/howto/wiki.md, docs/resources/publications.md
2020 titles were not title case
=> Fix 2020 Pulication Titles

docs/omc_team/physics.md
=> Basic Error Propagation

mkdocs.yml
=> Added link in sidebar

.github/workflows/test_build.yml, docs/packages/omc3/about.md, docs/packages/omc3/know_how.md, docs/packages/omc3/workflow.md, mkdocs.yml
Closes #49 
Write up of a simple guide for the `omc3` wokflow. Work in progress, contributions welcome.
=> OMC3 Workflow Page

docs/packages/about.md, docs/packages/development/contributing.md, docs/packages/development/howto_venv.md, mkdocs.yml
=> Content for Acc-Py and OMC Prod Python

docs/omc_team/methods.md, docs/packages/pylhc/about.md, docs/packages/pylhc/bpm_calibration.md, mkdocs.yml
The PR adds some physics, explanations and usage to the BPM calibration script.
=> Add documentation about BPM calibration

docs/procedures/general_checks.md, docs/procedures/info.md, mkdocs.yml
Including content from our discussion and Tobias' presentation on Monday.
Please proof-read!
=> Measurements checks page

docs/measurements/procedures/general_checks.md
=> Add Beam setup flag check

docs/measurements/procedures/rigid_waist_shift.md
Small additions: few steps and more details
=> Additional info in RWS Procedure

.github/workflows/documentation.yml, .github/workflows/test_build.yml, requirements.txt
=> CI Updates

docs/resources/logbook/2023_lhc.md
There is no summary for the second shift
=> Add two entries in LHC 2023 logbook

docs/resources/logbook/2024_lhc.md
same as #128 but from local branch
=> Lhc logbook 2024 03 11

docs/resources/logbook/2024_lhc.md
=> Shift 2024-03-12 LHC logbook

docs/resources/logbook/2024_lhc.md
Tested locally, links are fine.
=> Lhc logbook 2024 03 22 shift

docs/resources/logbook/2024_lhc.md
=> Shifts from last Sunday and Monday

docs/resources/logbook/2024_lhc.md
Entry for MD 13883. No actual shift plan due to the problems encountered, 
so I put the summary also in the plan link.
=> Entry for MD13883: Optics with HV crossing plane

docs/logbook/LHC/2025_lhc.md
Entry for second part of commissioning the ions cycle
=> LHC logbook 2025-05-18
